# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5339e2950505a2f2768e67aff3b1551feaee5f4bd7dc0b59b44f3b659298101227c22fb37c9e365c8899b15d511d23f5bf88c5949b32c4aaeb6bff33458721cf

test:
  secret_key_base: dbf891e58aed195d38d1295443854f7cfef8be2d7c67b4dfe20ec074026ab1abdde3389d112604093567613a04596d13d197c8754bdaafb6e4444bcba338b4b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
